# simple tasks to run racket files

task :default => :latest

task :latest do
  path = Dir["*/*.rkt"].sort.last

  sh "racket", "-t", "extras.rkt", path
end

task :all do
  homework = Dir["*/*.rkt"].sort.reverse

  homework.each do |path|
    sh "racket", "-t", "extras.rkt", path
  end
end
