# simple tasks to run racket files

task :default => :latest

def racket path
  sh "racket", path
end

task :latest do
  path = Dir["*/*.rkt"].sort.last

  racket path
end

task :all do
  homework = Dir["*/*.rkt"].sort.reverse

  homework.each do |path|
    racket path
  end
end
