# simple tasks to run racket files

task :default => :latest

def racket path
  sh "time", "racket", path
end

task :latest do
  path = Dir["*/*.rkt"].max_by { |f| File.mtime f }

  racket path
end

task :all do
  homework = Dir["*/*.rkt"].sort.reverse

  homework.each do |path|
    racket path
  end
end

task :test do
  homework = Dir["ch*/ch*.rkt"].sort.reverse

  homework.each do |path|
    racket path
  end
end

task :clean do
  a = Dir["**/*~"]
  rm_f a unless a.empty?
end
